// Generated by https://quicktype.io

export interface Activity {
  activityId:      number;
  name:            string;
  type:            Type;
  description:     string;
  accountId:       number;
  isDelete:        number;
  status:          number;
  formhtmlview_id: null;
  is_notified:     number;
  latitude:        null;
  longitude:       null;
  is_geotask:      number;
  sequence:        number;
  sitemap:         null;
}

export enum Type {
  Alert = "Alert",
  Empty = "",
  Form = "Form",
  Manual = "Manual",
  Scan = "Scan",
}
